name: nexi

description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.12
  firebase_database: ^11.3.10
  firebase_app_check: ^0.3.2+10
  flutter_bloc: ^9.1.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  email_validator: ^3.0.0
  freezed_annotation: ^3.1.0
  bloc: ^9.0.0
dev_dependencies:
  freezed: ^3.0.0-0.0.dev
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


